fx_version 'cerulean'
game 'gta5'
lua54 'yes'
author 'https://github.com/Pintta'
description 'https://github.com/Pintta/op-RealTime'
version '1.0.0'
client_script 'client.lua'
server_script 'server.lua'
